---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: versions
  - name: mongodb-compilation-bosh-release

outputs:
  - name: new_versions

run:
  path: mongodb-compilation-bosh-release/ci/jobs/bump-versions/scripts/propagate-versions.sh