---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: bosh-director-config
  - name: mongodb-compilation-bosh-release
  - name: mongodb-compilation-bosh-release-patched  
  - name: versions

outputs:
  - name: deployed  

run:
  path: mongodb-compilation-bosh-release/ci/compilation/deploy/scripts/deploy.sh

params:
  DEPLOYMENT_NAME: ""
  INSTANCE_GROUP: ""
  NETWORK: ""
  STEMCELL_TYPE: ""
  UUID: ""
  ALIAS: ""
  BOSH_RELEASE: ""  