name: mongodb-compilation
director_uuid: 8dd35958-abc4-46fc-9c96-f91c791bfeae

releases:
  - name: mongodb-compiler
    version: latest
 
update:
  canaries: 0
  canary_watch_time: 30000-240000
  update_watch_time:  30000-240000
  max_in_flight: 1 #<-- important to limit max in flight
  serial: false

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: 3445.11

instance_groups:
- name: make_archive
  release: mongodb-compiler
  lifecycle: errand
  azs: [z1]
  instances: 1
  vm_type: small
  env:
    bosh:
      swap_size: 0
  stemcell: trusty
  networks:
  - name: mongo1
  jobs:
  - name: make-tar
    release: mongodb-compiler
    properties: 
      mongodb-version: 3.4.6
