---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jraverdyorange/credhub-cli
    tag: latest

inputs:
  - name: mongodb-compilation-bosh-release
  - name: deployment-specs

outputs:
  - name: output

run:
  path: mongodb-compilation-bosh-release/ci/deployment/insertions-tests/scripts/get-root-pwd.sh