---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jraverdyorange/mongodb-cli
    tag: latest

inputs:
  - name: bosh-director-config
  - name: mongodb-compilation-bosh-release
  - name: deployment-specs
  
outputs:
  - name: filled

run:
  path: mongodb-compilation-bosh-release/ci/deployment/insertions-tests/scripts/insert-collection.sh