---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jraverdyorange/yml-tools
    tag: latest

inputs:
  - name: mongodb-compilation-bosh-release  
  - name: mongodb-src
  - name: rocksdb-src

outputs:
  - name: output
  
run:
  path: mongodb-compilation-bosh-release/ci/compilation/set-versions/scripts/fill-versions.sh