---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: garland/aws-cli-docker
    tag: latest

inputs:
  - name: mongodb-bosh-release-patched
  - name: mongodb-compilation-bosh-release

run:
  path: mongodb-compilation-bosh-release/ci/jobs/clone-blobstore/scripts/blobs-rename.sh

