---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: deployed
  - name: bosh-director-config
  - name: mongodb-compilation-bosh-release

run:
  path: mongodb-compilation-bosh-release/ci/jobs/acceptance-tests/scripts/run-acceptance-tests.sh