---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: mongodb-bosh-release
  - name: mongodb-compilation-bosh-release
  - name: bosh-director-config

outputs:
  - name: mongodb-bosh-release-patched   

run:
  path: mongodb-compilation-bosh-release/ci/clone-blobstore/clone-blobstore/scripts/get-release-blobs.sh

