---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: deployed
  - name: bosh-director-config
  - name: mongodb-compilation-bosh-release
  - name: mongodb-compilation-bosh-release-patched
  
outputs:
  - name: mongodb-compilation-bosh-release-archive

run:
  path: mongodb-compilation-bosh-release/ci/compilation/create-archive/scripts/make-archive.sh