---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jraverdyorange/aws-cli
    tag: latest

inputs:
  - name: mongodb-compilation-bosh-release
  - name: mongodb-compilation-bosh-release-patched
  - name: mongodb-compilation-bosh-release-archive
  - name: versions

outputs:
  - name: to-upload

run:
  path: mongodb-compilation-bosh-release/ci/compilation/create-archive/scripts/patch-config-files.sh