---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

outputs:
  - name: bosh-director-config

params:
  CA-CERT: ((bosh-server.ca))
  IP: ((bosh-server.ip))
  ALIAS: ((bosh-server.alias)) 
  USER: ((bosh-server.user))
  PASSWORD: ((bosh-server.password))

run:
  path: /bin/bash
  args:
    - -exc
    - |
      mkdir -p bosh-director-config
      cd bosh-director-config || exit 115
      cat > ./bosh_ca.crt <<EOF
      $CA-CERT
      EOF
      export BOSH_CONFIG=$PWD/bosh_config.yml
      bosh -e $IP alias-env $ALIAS --ca-cert=./bosh_ca.crt
      ( echo $USER ; echo $PASSWORD ) \
          | bosh -e $ALIAS log-in