---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: bosh-director-config
  - name: mongodb-compilation-bosh-release
  - name: mongodb-compilation-bosh-release-patched  
  - name: go-1.8-vendor-package

run:
  path: mongodb-compilation-bosh-release/ci/bin/create-release.sh