---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: mongodb-compilation-bosh-release

outputs:
  - name: bosh-director-config

run:
  path: mongodb-compilation-bosh-release/ci/bin/create-bosh-config.sh