---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: dl-versions    

outputs:
  - name: downloaded-src

run:
  path: mongodb-compilation-bosh-release/ci/bin/download-src.sh