---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: bosh-director-config

outputs:
  - name: to-upload

run:
  path: mongodb-compilation-bosh-release/ci/bin/make-archive.sh