---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: dl-versions
  - name: downloaded-src
  - name: bosh-director-config
  - name: mongodb-compilation-bosh-release

outputs:
  - name: to-upload

run:
  path: mongodb-compilation-bosh-release/ci/bin/upload-bosh.sh
