---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: garland/aws-cli-docker
    tag: latest

inputs:
  - name: to-upload

run:
  path: /bin/sh
  args:
    - -exc
    - |
      mkdir -p ~/.aws 
      cat > ~/.aws/credentials <<EOF 
      [default]
      aws_access_key_id=$ACCESS_KEY_ID
      aws_secret_access_key=$SECRET_ACCESS_KEY
      EOF

      cd to-upload || exit 666
      aws --endpoint-url $ENDPOINT_URL --no-verify-ssl s3 cp config/blobs.yml s3://$BUCKET/ci/blobs.yml
