---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jraverdyorange/aws-cli
    tag: latest

inputs:
  - name: mongodb-compilation-bosh-release
  - name: blobs-list

outputs:
  - name: output  


run:
  path: mongodb-compilation-bosh-release/ci/to-production/provide-blobs/scripts/copy-blobs-to-http-server.sh

