---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: bosh-director-config
  - name: mongodb-src
  - name: rocksdb-src  
  - name: mongodb-compilation-bosh-release
  - name: to-upload-pre
  
outputs:
  - name: to-upload

run:
  path: mongodb-compilation-bosh-release/ci/compilation/upload-src/scripts/update-config-files.sh
