---
jobs:
- name: get-mongodb-release
  serial: true
  plan:
    - aggregate:
      - get: mongodb-compilation-bosh-release
      - task: create-bosh-config
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: concourse/bosh-cli
              tag: latest
          outputs:
            - name: bosh-director-config
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                mkdir -p bosh-director-config
                cd bosh-director-config || exit 115
                cat > ./bosh_ca.crt <<EOF
                ((bosh-server.ca))
                EOF
                export BOSH_CONFIG=$PWD/bosh_config.yml
                bosh -e ((bosh-server.ip)) alias-env ((bosh-server.alias)) --ca-cert=./bosh_ca.crt
                ( echo ((bosh-server.user)) ; echo ((bosh-server.password)) ) \
                    | bosh -e ((bosh-server.alias)) log-in

      - task: check-current-stable-release
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: concourse/bosh-cli
              tag: latest
          inputs:
            - name: bosh-director-config
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                export BOSH_CONFIG=$PWD/bosh-director-config/bosh_config.yml
                cd mongodb-compilation-bosh-release/ci/get-new-release/bin/
                ./get_last_mongo_version.pl
                
resources:
  - name: mongodb-compilation-bosh-release
    type: git
    source:
      uri: https://github.com/orange-cloudfoundry/mongodb-compilation-boshrelease.git
      branch: Checking-new-release