---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: mongodb-compilation-bosh-release
  - name: bosh-director-config
  
run:
  path: mongodb-compilation-bosh-release/ci/deployment/backup-restore-test/scripts/run-shield-errand.sh