---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jraverdyorange/aws-cli
    tag: latest

inputs:
  - name: mongodb-compilation-bosh-release
run:
  path: mongodb-compilation-bosh-release/ci/common/scripts/blobstore-cleanup.sh

