---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jraverdyorange/aws-cli
    tag: latest

inputs:
  - name: mongodb-compilation-bosh-release
  - name: mongodb-bosh-release
  - name: versions

outputs:
  - name: mongodb-bosh-release-patched

run:
  path: mongodb-compilation-bosh-release/ci/common/scripts/get-config-files-mainrelease.sh

