---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jraverdyorange/aws-cli
    tag: latest

inputs:
  - name: mongodb-compilation-bosh-release
  - name: versions

outputs:
  - name: mongodb-compilation-bosh-release-patched

run:
  path: mongodb-compilation-bosh-release/ci/common/scripts/get-config-files.sh

params:
  ACCESS_KEY_ID: ""
  BUCKET: ""
  ENDPOINT_URL: ""
  MONGODB_VERSION: ""
  SECRET_ACCESS_KEY: ""
  SIGNATURE_VERSION: ""
  SKIP_SSL: ""
  SSL_CERT: ""
