---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: latest

inputs:
  - name: mongodb-compilation-bosh-release    

outputs:
  - name: output

run:
  path: mongodb-compilation-bosh-release/ci/common/scripts/initialize-keyval-ressource.sh
