---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jraverdyorange/aws-cli
    tag: latest

inputs:
  - name: versions
  - name: to-upload
  - name: mongodb-compilation-bosh-release

outputs:
  - name: uploaded  

run:
  path: mongodb-compilation-bosh-release/ci/common/scripts/upload-config-files.sh

params:
  ACCESS_KEY_ID: ""
  SECRET_ACCESS_KEY: ""
  ENDPOINT_URL: ""
  BUCKET: ""
  SKIP_SSL: ""
  SSL_CERT: ""
