---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: mongodb-compilation-bosh-release
  - name: mongodb-bosh-release
  
outputs:
  - name: versions
  
run:
  path: mongodb-compilation-bosh-release/ci/jobs/get-blob-sha1/scripts/get-blob-sha1.sh