---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: garland/aws-cli-docker
    tag: latest

inputs:
  - name: mongodb-bosh-release
  - name: mongodb-compilation-bosh-release
  - name: mongodb-compilation-bosh-release-patched

outputs:
  - name: mongodb-bosh-release-patched

run:
  path: mongodb-compilation-bosh-release/ci/jobs/deploy-346/scripts/get-config-files-mainrelease.sh

