---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: mongodb-bosh-release-patched
  - name: mongodb-compilation-bosh-release
  - name: bosh-director-config

outputs:
  - name: deployed   

run:
  path: mongodb-compilation-bosh-release/ci/jobs/deploy-346/scripts/deploy-rs.sh