---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: garland/aws-cli-docker
    tag: latest

inputs:
  - name: mongodb-compilation-bosh-release

outputs:
  - name: mongodb-compilation-bosh-release-patched

run:
  path: mongodb-compilation-bosh-release/ci/jobs/common/scripts/get-config-files.sh

