---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: mongodb-compilation-bosh-release
  - name: mongodb-version

outputs:
  - name: versions
  
run:
  path: mongodb-compilation-bosh-release/ci/to-production/set-versions/scripts/set-versions.sh