---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: bosh-director-config
  - name: mongodb-compilation-bosh-release
  - name: mongodb-compilation-bosh-release-patched  
  - name: versions

outputs:
  - name: created  

run:
  path: mongodb-compilation-bosh-release/ci/compilation/create-release/scripts/create-release.sh