name: ((deployment))
director_uuid: ((director_uuid))

releases:
  - name: ((release))
    version: latest
 
update:
  canaries: 0
  canary_watch_time: 30000-240000
  update_watch_time:  30000-240000
  max_in_flight: 1 #<-- important to limit max in flight
  serial: false

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: ((instance_group))
  release: ((release))
  lifecycle: errand
  azs: [z1]
  instances: 1
  vm_type: small
  env:
    bosh:
      swap_size: 0
  stemcell: trusty
  networks:
  - name: ((network))
  jobs:
  - name: make-tar
    release: ((release))
    properties: 
      mongodb-version: ((version))
