name: ((appli))
director_uuid: 8dd35958-abc4-46fc-9c96-f91c791bfeae

releases:
  - name: ((mongodb-release))
    version: latest
  - name: prometheus
    version: latest
  - name: shield
    version: latest
 
update:
  canaries: 1
  canary_watch_time: 30000-240000
  update_watch_time:  30000-240000
  max_in_flight: 1 #<-- important to limit max in flight
  serial: false

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: mongod
  release: ((mongodb-release))
  azs: [z1]
  instances: 3 # 
  vm_type: ((vm-type))
  env:
    bosh:
      swap_size: 0
  stemcell: trusty
  networks:
  - name: ((deployments-network))
  persistent_disk_type: ((persistent-disk-type))
  env:
    persistent_disk_fs: xfs
  jobs:
  - name: mongod
    release: ((mongodb-release))
    properties: 
      node_role: rs
      require_ssl: 0
      replication:
        enable: 1
        key: ((mongo_keyfile_content))
      root_username: ((root-username))
      root_password: ((mongo_root_password))
      admin_password: ((mongo_admin_password))
      server_certificate: 
        ca: ((mongo_ca.ca))
        private_key: ((mongo_ca.private_key))
        certificate: ((mongo_ca.certificate))
  
  - name: import
    release: shield
    properties:
      import:
        core: ((shield-url))
        token: ((shield-token))
        ca: ((/bosh-jra/shield-test/shield-ca.certificate))
        tenants:
        - name: ((shield-tenant))
          systems:
            - name: ((appli))-(ip)
              agent:  (ip):5444
              plugin: mongo
              config: 
                mongo_bindir: /var/vcap/packages/mongodb/bin
                mongo_user: ((root-username))
                mongo_password: ((mongo_root_password))
              summary: "test shield"
              jobs:
                - name: (ip)-backup-test
                  when: "every 8 hours from 0:15"
                  policy: Short-Term
                  storage: ((shield-storage))
                  paused: yes
    
  - name: shield-agent
    release: shield
    properties:
      name: ((appli))
      shield-url: ((shield-url))
      require-shield-core: false
      core:
        ca: ((/bosh-jra/shield-test/shield-ca.certificate))
    consumes:
      shield: { from: shield, deployment: shield-test }
      
  - name: mongodb_exporter
    release: prometheus
    properties:
      mongodb_exporter:
        mongodb:
          uri: mongodb://((root-username)):((mongo_root_password))@localhost:((mongo-port))?authSource=admin
        web:
          port: 9001  
        collect_oplog: true
        collect_replset: true

- name: acceptance-tests
  release: ((mongodb-release))
  lifecycle: errand
  azs: [z1]
  instances: 1
  jobs:
    - name: mongodb-acceptance-tests
      release: ((mongodb-release))
  vm_type: ((vm-type))
  stemcell: trusty
  networks:
    - name: ((deployments-network))

variables:
  - name: mongo_admin_password
    type: password
  - name: mongo_root_password
    type: password
  - name: mongo_keyfile_content
    type: password
    options: 
      length: 200  
  - name: /internalCA
    type: certificate
    options:
      is_ca: true
      common_name: internalCA
  - name: mongo_ca
    type: certificate
    options:
      ca: /internalCA
      common_name: mongo-cert
#      extended_key_usage:
#      - server_auth
#      - client_auth
#    alternative_names: [((internal_ip))]
