name: ((appli))
director_uuid: 8dd35958-abc4-46fc-9c96-f91c791bfeae

releases:
  - name: mongodb-services
    version: latest
  - name: prometheus
    version: latest
  - name: shield
    version: latest
 
update:
  canaries: 1
  canary_watch_time: 30000-240000
  update_watch_time:  30000-240000
  max_in_flight: 1 #<-- important to limit max in flight
  serial: false

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: 3445.11

instance_groups:
- name: mongod
  release: mongodb-services
  azs: [z1]
  instances: 3 # 
  vm_type: small
  env:
    bosh:
      swap_size: 0
  stemcell: trusty
  networks:
  - name: mongo1
  persistent_disk_type: small
  env:
    persistent_disk_fs: xfs
  jobs:
  - name: mongod
    release: mongodb-services
    properties: 
      node_role: rs
      require_ssl: 0
      replication:
        enable: 1
        key: ((mongo_keyfile_content))
      root_password: ((mongo_root_password))
      admin_password: ((mongo_admin_password))
      server_certificate: 
        ca: ((mongo_ca.ca))
        private_key: ((mongo_ca.private_key))
        certificate: ((mongo_ca.certificate))
  - release: shield
    name: shield-agent
    properties:
      autoprovision: true # https://10.165.0.21
      targets:
        mongodb:
          plugin: mongo
          config:
            mongo_user: MongoRoot
            mongo_password: ((mongo_root_password))
            mongo_port: "27017"
            mongo_bindir: "/var/vcap/packages/mongodb/bin"
    consumes:
      shield-daemon: { from: shield-daemon, deployment: shield }
  - name: mongodb_exporter
    release: prometheus
    properties:
      mongodb_exporter:
        mongodb:
          uri: mongodb://MongoRoot:((mongo_root_password))@localhost:27017?authSource=admin
        web:
          port: 9001  
        collect_oplog: true
        collect_replset: true
properties:
  aliases:
    bbs.service.cf.internal:
    - "*.database-z1.diego1.cf-cfapps-io2-diego.bosh"
    - "*.database-z2.diego2.cf-cfapps-io2-diego.bosh"

variables:
  - name: mongo_admin_password
    type: password
  - name: mongo_root_password
    type: password
  - name: mongo_keyfile_content
    type: password
    options: 
      length: 200  
  - name: /internalCA
    type: certificate
    options:
      is_ca: true
      common_name: internalCA
  - name: mongo_ca
    type: certificate
    options:
      ca: /internalCA
      common_name: mongo-cert
#      extended_key_usage:
#      - server_auth
#      - client_auth
#    alternative_names: [((internal_ip))]
