---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jraverdyorange/mongodb-cli
    tag: latest

inputs:
  - name: mongodb-compilation-bosh-release
  - name: versions
  - name: deployment-specs
  
run:
  path: mongodb-compilation-bosh-release/ci/deployment/version-upgrade/scripts/check-mongo-version.sh

