---
jobs:
- name: compile_mongo
  serial: true
  plan:
    - aggregate:
      - get: mongodb-compilation-bosh-release
      - get: go-1.8-vendor-package
      - task: create-bosh-config
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: concourse/bosh-cli
              tag: latest
          outputs:
            - name: bosh-director-config
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                mkdir -p bosh-director-config
                cd bosh-director-config || exit 115
                cat > ./bosh_ca.crt <<EOF
                ((bosh-server.ca))
                EOF
                export BOSH_CONFIG=$PWD/bosh_config.yml
                bosh -e ((bosh-server.ip)) alias-env ((bosh-server.alias)) --ca-cert=./bosh_ca.crt
                ( echo ((bosh-server.user)) ; echo ((bosh-server.password)) ) \
                    | bosh -e bosh-concourse log-in

    - task: create-release
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: concourse/bosh-cli
            tag: latest
        inputs:
          - name: bosh-director-config
          - name: mongodb-compilation-bosh-release
          - name: go-1.8-vendor-package
        run:
          path: /bin/bash
          args:
            - -exc
            - |
              export BOSH_CONFIG=$PWD/bosh-director-config/bosh_config.yml
              cd mongodb-compilation-bosh-release|| exit 115
              bosh -e bosh-concourse create-release # --force
              bosh -e bosh-concourse upload-release
              bosh -e bosh-concourse -d mongodb-compilation -n deploy manifest.yml -o ci/concourse-network.yml

    - task: run-errand
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: concourse/bosh-cli
            tag: latest
        inputs:
          - name: bosh-director-config
          - name: mongodb-compilation-bosh-release
        run:
          path: /bin/bash
          args:
            - -exc
            - |
              export BOSH_CONFIG=$PWD/bosh-director-config/bosh_config.yml
              cd mongodb-compilation-bosh-release || exit 115
              bosh -e bosh-concourse -d mongodb-compilation -n run-errand make-tar --keep-alive
              bosh -e bosh-concourse -d mongodb-compilation scp /var/vcap/store/$JOB_NAME/archive/mongodb-linux-x86_64-*.tar.gz .
              file=`ls mongodb-linux-x86_64-*.tar.gz`
              bosh -e bosh-concourse add-blob $file mongodb/$file
              bosh -e bosh-concourse upload-blobs
              bosh -e bosh-concourse -n delete-vm $(bosh -e bosh-concourse -d mongodb-compilation vms --column="vm cid")
              bosh -e bosh-concourse -n delete-disk $(bosh -e bosh-concourse -d mongodb-compilation disks --orphaned --column="disk cid")

resources:
  - name: mongodb-compilation-bosh-release
    type: git
    source:
      uri: https://github.com/orange-cloudfoundry/mongodb-compilation-boshrelease.git
      branch: Initial-commit
  - name: go-1.8-vendor-package
    type: git
    source:
      uri: https://github.com/bosh-packages/golang-release.git