---
jobs:
- name: compile_mongo
  serial: true
  plan:
    - aggregate:
      - get: mongodb-compilation-bosh-release
      - task: create-bosh-config
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: concourse/bosh-cli
              tag: latest
          outputs:
            - name: bosh-director-config
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                mkdir -p bosh-director-config
                cd bosh-director-config || exit 115
                cat > ./bosh_ca.crt <<EOF
                -----BEGIN CERTIFICATE-----
                MIIDEzCCAfugAwIBAgIQQjCfQi7CxoQv26iV1bvWCTANBgkqhkiG9w0BAQsFADAz
                MQwwCgYDVQQGEwNVU0ExFjAUBgNVBAoTDUNsb3VkIEZvdW5kcnkxCzAJBgNVBAMT
                AmNhMB4XDTE3MTEwMzEwNTIyNVoXDTE4MTEwMzEwNTIyNVowMzEMMAoGA1UEBhMD
                VVNBMRYwFAYDVQQKEw1DbG91ZCBGb3VuZHJ5MQswCQYDVQQDEwJjYTCCASIwDQYJ
                KoZIhvcNAQEBBQADggEPADCCAQoCggEBANz6S8KG714kjTtFq44REnqTMshYtSN/
                rHXvSkDXu46aLcgWoGT+Ak2RO9QOUTVNv54pk7ogx4KTwsjeOi0hSgsvPWYytY4Q
                MWTnQzKa9fsHRnybsLDZ+RK+qUKBpNGwj9+k64WSAVEPZdTGTNywlF6ArJmXg9v3
                /I99tvUk49QgQxahyIxRHpoF+sc5iKgwChjLS/hZ1+hWOYDE+SepvTSQQigIbmxo
                V7g7n1OXVygf2WbX7FksRV82ajyt4lUYj32r9m8nfp7gAICxDvdBAwMzDigcd0H0
                wsGWV2+y6AywyXU/UfPx2h/MUOcvkJvEsUCjKFfyNzPfbTkcZAPuJPkCAwEAAaMj
                MCEwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQEL
                BQADggEBAD7FJAA627Z3YdrfnPxzaIpr9Is9QvIbTRIsg3ukzEOZfsKRV7s/Oarp
                T6AsuaUIgCmFB+uDzy6K2+wHq6ZlMoIHJ9loIpfTqJ1zOHW9tBeLCdX7u3omZB1n
                jMATCYEyYHCnS+1V8mvFddC9JUqzO+JOQHTK6HXW5p77MTo17UiFY3kzI/Gq+Hb/
                9v8lHqau/3O0y8W1PJlz+T+V6SbZpbrHiwgz0Ws1phTpV6rov2a4lIvXxOUKHV3s
                yZrN8ij1sQLXboU/KQvgbWkNZxMkkt+kGVsBnB1NZbcgzQJZxhrV1I4I14uo7a9j
                wAwY/0VT2nBvGJY+EceSsddWraST+OI=
                -----END CERTIFICATE-----
                EOF
                export BOSH_CONFIG=$PWD/bosh_config.yml
                bosh -e ((bosh-server.ip)) alias-env ((bosh-server.alias)) --ca-cert=./bosh_ca.crt
                ( echo ((bosh-server.user)) ; echo ((bosh-server.password)) ) \
                    | bosh -e bosh-concourse log-in

    - task: create-release
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: concourse/bosh-cli
            tag: latest
        inputs:
          - name: bosh-director-config
          - name: mongodb-compilation-bosh-release
        run:
          path: /bin/bash
          args:
            - -exc
            - |
              export BOSH_CONFIG=$PWD/bosh-director-config/bosh_config.yml
              cd mongodb-compilation-bosh-release|| exit 115
              bosh -e bosh-concourse create-release # --force
              bosh -e bosh-concourse upload-release
              bosh -e bosh-concourse -d mongodb-compilation -n deploy manifest.yml

    - task: run-errand
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: concourse/bosh-cli
            tag: latest
        inputs:
          - name: bosh-director-config
          - name: mongodb-compilation-bosh-release
        run:
          path: /bin/bash
          args:
            - -exc
            - |
              export BOSH_CONFIG=$PWD/bosh-director-config/bosh_config.yml
              cd mongodb-bosh-release || exit 115
              bosh -e bosh-concourse -d mongodb-compilation -n run-errand make-tar --keep-alive           

resources:
  - name: mongodb-compilation-bosh-release
    type: git
    source:
      uri: https://github.com/orange-cloudfoundry/mongodb-compilation-boshrelease.git
      branch: master