---
resource_types:
  - name: keyval
    type: docker-image
    source:
      repository: regevbr/keyval-resource
      
resources:

  - name: mongodb-compilation-bosh-release
    type: git
    source:
      uri: https://github.com/orange-cloudfoundry/mongodb-compilation-boshrelease.git
      branch: ((git.branch))

  - name: mongodb-version
    type: semver
    source: 
      initial_version: 1.0.0
      driver: git
      uri: https://github.com/orange-cloudfoundry/mongodb-compilation-boshrelease.git
      branch: ((git.branch))
      file: compiled_version
      username: ((git.username))
      password: ((git.password))
      git_user: "((git.git_user)) <((git.email))>"

  - name: rocksdb-version
    type: semver
    source: 
      initial_version: 1.0.0
      driver: git
      uri: https://github.com/orange-cloudfoundry/mongodb-compilation-boshrelease.git
      branch: ((git.branch))
      file: compiled_version
      username: ((git.username))
      password: ((git.password))
      git_user: "((git.git_user)) <((git.email))>"

  - name: dl-versions
    type: keyval

jobs:
- name: check-versions
  serial: true
  plan:
    - aggregate:
      - get: mongodb-compilation-bosh-release       
      - get: mongodb-version
      - get: rocksdb-version

    - task: check-versions
      file: mongodb-compilation-bosh-release/ci/tasks/check-versions.yml

    - put: dl-versions
      params: {file: dl-versions/dl-versions.properties}
           
- name: upload-src
  serial: true
  plan:
    - aggregate:
      - get: mongodb-compilation-bosh-release
      - task: create-bosh-config
        file: mongodb-compilation-bosh-release/ci/create-bosh-config.yml

    - get: dl-versions
      trigger: true
      passed: [check-versions]

    - task: download-src
      file: mongodb-compilation-bosh-release/ci/tasks/download-src.yml

    - task: upload-bosh
      file: mongodb-compilation-bosh-release/ci/tasks/upload-bosh.yml

    - task: upload-blob-list
      file: mongodb-compilation-bosh-release/ci/tasks/upload-blob-list.yml