---
resource_types:
  - name: keyval
    type: docker-image
    source:
      repository: swce/keyval-resource
      
resources:

  - name: mongodb-compilation-bosh-release
    type: git
    source:
      uri: https://github.com/orange-cloudfoundry/mongodb-compilation-boshrelease.git
      branch: ((mongodb-compilation-boshrelease-repo.branch))

  - name: mongodb-bosh-release
    type: git
    source:
      uri: https://github.com/orange-cloudfoundry/mongodb-boshrelease.git
      branch: ((mongodb-boshrelease-repo.branch))    

  - name: mongodb-version
    type: semver
    source: 
      initial_version: 1.0.0
      driver: git
      uri: https://github.com/orange-cloudfoundry/mongodb-compilation-boshrelease.git
      branch: ((mongodb-compilation-boshrelease-repo.branch))
      file: mongodb_compiled_version
      username: ((mongodb-compilation-boshrelease-repo.username))
      password: ((mongodb-compilation-boshrelease-repo.password))
      git_user: "((mongodb-compilation-boshrelease-repo.git_user)) <((mongodb-compilation-boshrelease-repo.email))>"

  - name: rocksdb-version
    type: semver
    source: 
      initial_version: 1.0.0
      driver: git
      uri: https://github.com/orange-cloudfoundry/mongodb-compilation-boshrelease.git
      branch: ((mongodb-compilation-boshrelease-repo.branch))
      file: rocksdb_compiled_version
      username: ((mongodb-compilation-boshrelease-repo.username))
      password: ((mongodb-compilation-boshrelease-repo.password))
      git_user: "((mongodb-compilation-boshrelease-repo.git_user)) <((mongodb-compilation-boshrelease-repo.email))>"

jobs:
- name: deploy-346
  serial: true
  plan:
    - aggregate:
      - get: mongodb-bosh-release
      - get: mongodb-compilation-bosh-release
      - get: mongodb-version
        trigger: true
      - get: rocksdb-version
        trigger: true
    
    - task: get-config-files-mainrelease
      file: mongodb-compilation-bosh-release/ci/jobs/common/tasks/get-config-files-mainrelease.yml
      params:
        ACCESS_KEY_ID: ((S3.access_key_id))
        SECRET_ACCESS_KEY: ((S3.secret_access_key))
        ENDPOINT_URL: ((S3.endpoint-url))
        BUCKET: ((S3.bucket))   
