---
resource_types:
  - name: keyval
    type: docker-image
    source:
      repository: swce/keyval-resource
      
resources:

  - name: mongodb-compilation-bosh-release
    type: git
    source:
      uri: https://github.com/orange-cloudfoundry/mongodb-compilation-boshrelease.git
      branch: ((mongodb-compilation-boshrelease-repo.branch))

  - name: mongodb-bosh-release
    type: git
    source:
      uri: https://github.com/orange-cloudfoundry/mongodb-boshrelease.git
      branch: ((mongodb-boshrelease-repo.branch))    

  - name: mongodb-version
    type: semver
    source: 
      initial_version: 1.0.0
      driver: git
      uri: https://github.com/orange-cloudfoundry/mongodb-compilation-boshrelease.git
      branch: ((mongodb-compilation-boshrelease-repo.branch))
      file: mongodb_compiled_version
      username: ((mongodb-compilation-boshrelease-repo.username))
      password: ((mongodb-compilation-boshrelease-repo.password))
      git_user: "((mongodb-compilation-boshrelease-repo.git_user)) <((mongodb-compilation-boshrelease-repo.email))>"

  - name: rocksdb-version
    type: semver
    source: 
      initial_version: 1.0.0
      driver: git
      uri: https://github.com/orange-cloudfoundry/mongodb-compilation-boshrelease.git
      branch: ((mongodb-compilation-boshrelease-repo.branch))
      file: rocksdb_compiled_version
      username: ((mongodb-compilation-boshrelease-repo.username))
      password: ((mongodb-compilation-boshrelease-repo.password))
      git_user: "((mongodb-compilation-boshrelease-repo.git_user)) <((mongodb-compilation-boshrelease-repo.email))>"

  - name: deployed
    type: keyval

  - name: deployment-specs
    type: keyval  
  
  - name: filled
    type: keyval

  - name: removed
    type: keyval

jobs:
- name: deploy-346
  serial: true
  plan:
    - get: mongodb-bosh-release
    - get: mongodb-compilation-bosh-release  
    - aggregate:
      - get: mongodb-version
        trigger: true
      - get: rocksdb-version
        trigger: true
      - task: create-bosh-config
        file: mongodb-compilation-bosh-release/ci/jobs/common/tasks/create-bosh-config.yml
        params:
          CA_CERT:  ((bosh-server.ca))
          IP:       ((bosh-server.ip))
          ALIAS:    ((bosh-server.alias)) 
          USER:     ((bosh-server.user))
          PASSWORD: ((bosh-server.password)) 

    - task: get-config-files
      file: mongodb-compilation-bosh-release/ci/jobs/common/tasks/get-config-files.yml
      params:
        ACCESS_KEY_ID:      ((compilation-blobstore.access_key_id))
        SECRET_ACCESS_KEY:  ((compilation-blobstore.secret_access_key))
        ENDPOINT_URL:       ((compilation-blobstore.endpoint-url))
        BUCKET:             ((compilation-blobstore.bucket))       
    
    - task: get-config-files-mainrelease
      file: mongodb-compilation-bosh-release/ci/jobs/deploy-346/tasks/get-config-files-mainrelease.yml
      params:
        ACCESS_KEY_ID:            ((mongodb-release-blobstore.access_key_id))
        SECRET_ACCESS_KEY:        ((mongodb-release-blobstore.secret_access_key))
        ENDPOINT_URL:             ((mongodb-release-blobstore.endpoint-url))
        BUCKET:                   ((mongodb-release-blobstore.bucket))
        COMPIL_ACCESS_KEY_ID:     ((compilation-blobstore.access_key_id))
        COMPIL_SECRET_ACCESS_KEY: ((compilation-blobstore.secret_access_key))
        COMPIL_ENDPOINT_URL:      ((compilation-blobstore.endpoint-url))
        COMPIL_BUCKET:            ((compilation-blobstore.bucket))

    - task: deploy-rs
      file: mongodb-compilation-bosh-release/ci/jobs/deploy-346/tasks/deploy-rs.yml      
      params:
        CA_CERT:              ((bosh-server.ca))
        IP:                   ((bosh-server.ip))
        ALIAS:                ((bosh-server.alias)) 
        USER:                 ((bosh-server.user))
        PASSWORD:             ((bosh-server.password))
        RELEASE_NAME:         ((deployment.tests.name))
        DEPLOYMENT_NAME:      ((deployment.tests.name))
        DEPLOYMENT_NETWORK:   ((deployment.tests.network))
        SHIELD_URL:           ((deployment.tests.shield.core))
        SHIELD_TOKEN:         ((deployment.tests.shield.token))
        SHIELD_TENANT:        ((deployment.tests.shield.tenant))
        SHIELD_STORAGE:       ((deployment.tests.shield.storage))
        MONGO_PORT:           ((deployment.tests.mongod.port))
        PERSISTENT_DISK_TYPE: ((deployment.tests.mongod.persistent-disk-type))
        VM_TYPE:              ((deployment.tests.mongod.vm-type))
        ROOT_USERNAME:        ((deployment.tests.mongod.root-username))

    - put: deployed
      params: { file: deployed/keyval.properties }    


- name: insertion-tests
  serial: true
  plan:
    - get: deployed
      trigger: true
      passed: [deploy-346]

    - get: mongodb-compilation-bosh-release
    - aggregate:
      - task: create-bosh-config
        file: mongodb-compilation-bosh-release/ci/jobs/common/tasks/create-bosh-config.yml
        params:
          CA_CERT:  ((bosh-server.ca))
          IP:       ((bosh-server.ip))
          ALIAS:    ((bosh-server.alias)) 
          USER:     ((bosh-server.user))
          PASSWORD: ((bosh-server.password))

    - task: get-mongo-pwd
      file: mongodb-compilation-bosh-release/ci/jobs/insertions-tests/tasks/get-root-pwd.yml
      params:
        BOSH_ALIAS: ((bosh-server.alias))
        IP:         ((deployment.tests.credhub.ip))
        PORT:       ((deployment.tests.credhub.port))
        USER:       ((deployment.tests.credhub.username))
        PASSWORD:   ((deployment.tests.credhub.password))
        VAR:        mongo_root_password

    - put: deployment-specs
      params: { file: output/keyval.properties}

    - task: get-deployment-ips
      file: mongodb-compilation-bosh-release/ci/jobs/insertions-tests/tasks/get-deployment-ips.yml
      params:
        CA_CERT:  ((bosh-server.ca))
        IP:       ((bosh-server.ip))
        ALIAS:    ((bosh-server.alias)) 
        USER:     ((bosh-server.user))
        PASSWORD: ((bosh-server.password))

    - put: deployment-specs
      params: { file: output/keyval.properties}    

    - task: insert-collection
      file: mongodb-compilation-bosh-release/ci/jobs/insertions-tests/tasks/insert-collection.yml
      params:
        USER: ((deployment.tests.mongod.root-username))
        PORT: ((deployment.tests.mongod.port))

    - put: filled
      params: { file: filled/keyval.properties }

- name: backup-restore-test
  serial: true
  plan:
    - get: filled
      trigger: true
      passed: [insertion-tests]

    - get: deployment-specs

    - get: mongodb-compilation-bosh-release
    - aggregate:
      - task: create-bosh-config
        file: mongodb-compilation-bosh-release/ci/jobs/common/tasks/create-bosh-config.yml
        params:
          CA_CERT:  ((bosh-server.ca))
          IP:       ((bosh-server.ip))
          ALIAS:    ((bosh-server.alias)) 
          USER:     ((bosh-server.user))
          PASSWORD: ((bosh-server.password))

    - task: shield-clean-up
      file: mongodb-compilation-bosh-release/ci/jobs/backup-restore-test/tasks/shield-clean-up.yml
      params:
        SHIELD_CA:          ((deployment.tests.shield.ca))
        SHIELD_CORE_TOKEN:  ((deployment.tests.shield.token))
        SHIELD_CORE:        ((deployment.tests.shield.core))
        SHIELD_TENANT:      ((deployment.tests.shield.tenant))
        SHIELD_TARGET:      ((deployment.tests.name))

    - task: run-shield-import-errand
      file: mongodb-compilation-bosh-release/ci/jobs/backup-restore-test/tasks/run-shield-errand.yml
      params:
        ALIAS:      ((bosh-server.alias))
        DEPLOYMENT: ((deployment.tests.name))

    - task: backup
      file: mongodb-compilation-bosh-release/ci/jobs/backup-restore-test/tasks/backup.yml
      params:
        SHIELD_CA:          ((deployment.tests.shield.ca))
        SHIELD_CORE_TOKEN:  ((deployment.tests.shield.token))
        SHIELD_CORE:        ((deployment.tests.shield.core))
        SHIELD_TENANT:      ((deployment.tests.shield.tenant))
 
- name: delete-deployment
  serial: false
  plan:

    - get: mongodb-compilation-bosh-release
    - task: create-bosh-config
      file: mongodb-compilation-bosh-release/ci/jobs/common/tasks/create-bosh-config.yml
      params:
        CA_CERT:  ((bosh-server.ca))
        IP:       ((bosh-server.ip))
        ALIAS:    ((bosh-server.alias)) 
        USER:     ((bosh-server.user))
        PASSWORD: ((bosh-server.password))

    - get: deployed
      trigger: false
      passed: [deploy-346]

    - task: remove-deployment
      file: mongodb-compilation-bosh-release/ci/jobs/remove-deployment/tasks/remove-deployment.yml      
      params:
        CA_CERT:              ((bosh-server.ca))
        IP:                   ((bosh-server.ip))
        ALIAS:                ((bosh-server.alias)) 
        USER:                 ((bosh-server.user))
        PASSWORD:             ((bosh-server.password))
        RELEASE_NAME:         ((deployment.tests.name))
        DEPLOYMENT_NAME:      ((deployment.tests.name))
        DEPLOYMENTS_NETWORK:  ((deployment.tests.network))
        SHIELD_URL:           ((deployment.tests.shield.core))
        MONGO_PORT:           ((deployment.tests.mongod.port))
        PERSISTENT_DISK_TYPE: ((deployment.tests.mongod.persistent-disk-type))
        VM_TYPE:              ((deployment.tests.mongod.vm-type))
        ROOT_USERNAME:        ((deployment.tests.mongod.root-username))

    - put: removed
      params: { file: removed/keyval.properties }
    