---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: mongodb-compilation-bosh-release
  - name: mongodb-version
  - name: rocksdb-version
  
outputs:
  - name: versions
  
run:
  path: mongodb-compilation-bosh-release/ci/jobs/check-versions/scripts/check-versions.sh