---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jraverdyorange/aws-cli
    tag: latest

inputs:
  - name: mongodb-compilation-bosh-release
  - name: ci
  - name: to_rename

run:
  path: mongodb-compilation-bosh-release/ci/initialize-compilation-blobstore/get-dependencies/scripts/upload-config-files.sh
