---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: compiled
  - name: bosh-director-config
  - name: mongodb-compilation-bosh-release
  - name: mongodb-compilation-bosh-release-patched
  
outputs:
  - name: to-upload
  - name: versions

run:
  path: mongodb-compilation-bosh-release/ci/jobs/create-archive/scripts/make-archive.sh