---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jraverdyorange/mongodb-cli
    tag: latest

inputs:
  - name: mongodb-compilation-bosh-release
  - name: deployment-specs
  - name: filled
  
run:
  path: mongodb-compilation-bosh-release/ci/jobs/backup-restore-test/scripts/test-restoration.sh