- type: replace
  path: /stemcells/alias=trusty/alias
  value: centos

- type: replace
  path: /stemcells/alias=centos/os
  value: centos-7

- type: replace  
  path: /instance_groups/name=((instance_group))/stemcell
  value: centos