---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jraverdyorange/credhub-cli
    tag: latest

inputs:
  - name: mongodb-compilation-bosh-release

outputs:
  - name: mongo-passwd

run:
  path: mongodb-compilation-bosh-release/ci/jobs/insertions-tests/scripts/get-root-pwd.sh